services:
  wordle-application:
    container_name: wordle-application 
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "50010:50010"